### ISSUE TITLE
swaddle apt package: error on line 17945

### ISSUE THREAD

**Issue by ringods** [raphaelcohn/swaddle#23]
Hello,

I have swaddle installed via the APT repository on an Ubuntu 14.04. When I run swaddle, I always get this error:

```
/usr/bin/swaddle: 17945: /usr/bin/swaddle: Syntax error: "(" unexpected (expecting "}")
```

Is there an error in the script?

**Comment by raphaelcohn** [comment]
Yes, it's a code generation issue to do with bash versions. In essence, when a function is defined inside a function with bash, and that code is exported using declare, bash sometimes gets it wrong. [bish-bosh](https://github.com/raphaelcohn/bish-bosh) has had the same problem.

I'll make a new release shortly. For now, you can change the first line of `/usr/bin/swaddle` from:-

```bash
#!/usr/bin/env sh
```
to

```bash
#!/usr/bin/env bash
```

eg using `sudo sed -i -e 's;^#!/usr/bin/env sh$;#!/usr/bin/env bash;' /usr/bin/swaddle`

**Comment by raphaelcohn** [comment]
I've made a new [release](https://github.com/raphaelcohn/swaddle/releases/tag/release_2015.0422.1105-1). You should be able to just do `sudo apt-get update` (but revert the line change above first).

**Comment by ringods** [comment]
Tnx!! It works.
