### ISSUE TITLE
Adding debian amd64 specific content?

### ISSUE THREAD

**Issue by ringods** [raphaelcohn/swaddle#27]
In the [docs](https://github.com/raphaelcohn/swaddle#how-to-use-it), I see this folder structure:

```
            deb\             # Create this, and you're making debian packages
                deb.conf     # Debian specific settings, if any; entirely optional
                skeleton\    # As above. Merged using rsync. Allows per-package-kind, per-architecture-variant file differences
                body\        # As above. Merged using rsync.
                    …
```
I create my folder structure like this:
```
swaddling\my_project\
   swaddling.conf
   deb\
       deb.conf
       body\
           amd64\
               opt\
                   ...
```
But when running `swaddle`, I get this:
```
/usr/bin/swaddle: 24718: /usr/bin/swaddle: configure_validateAptArchitecture: not found
```
Having the `amd64` folder immediately under `deb` prevents the error but doesn't put my files in my package.

So where should I put Debian amd64 specific content to be included in my package?

**Comment by raphaelcohn** [comment]
Hmmm - do you also have an `all` folder? If so, that might be it. Could you add `set -x` to the second line of `/usr/bin/swaddle` and send me a gist? I'll take a look. I'm on a call right now, so won't be until 5pm BST.

**Comment by ringods** [comment]
https://gist.github.com/ringods/f1768bab01fe0bb2c6d1

**Comment by raphaelcohn** [comment]
This turns out to be a typo - a classic problem is dynamic languages.
Pushing a release now to fix it.

**Comment by raphaelcohn** [comment]
[Released](https://github.com/raphaelcohn/swaddle/releases/tag/release_2015.0429.1637-1)

**Comment by ringods** [comment]
Installed the new release. I put my files in `deb\body\amd64` and run `swaddle`. First of all, it takes quite a bit longer to run now but unfortunately, it ends with:

```
/usr/bin/swaddle: 1: eval: swaddle_build_configuration_value_swaddle_deb_no_initialised: parameter not set
```

Need a gist?

**Comment by raphaelcohn** [comment]
Yes please; shell error messages are wonderfully useless. I've only got a little time tonight; then I'm with clients / travelling until very late Friday, and child rearing Sat / Sun.

**Comment by raphaelcohn** [comment]
I wonder if there's a mistake in your configuration, and the configure validation code isn't catching it. Regardless, a gist should show it.

**Comment by ringods** [comment]
https://gist.github.com/ringods/6beecae64b6a8dde63a0

**Comment by raphaelcohn** [comment]
Well, I've got the programmer's dinner in, so I'll get started...

**Comment by ringods** [comment]
I have the impression that the default value `no` for keys `multiarch`, `essential` or `build_essential` in namespace `swaddle_deb` is interpreted as a key rather than a value somewhere.

**Comment by raphaelcohn** [comment]
Found the bug. It's in the Debian multiarch handling. In essence, I'm calling a function which expects an array, but the multiarch setting is a boolean (this changed at some point as my understanding of multiarch changed; personally I loathe multiarch binaries, esp on x86_64, now that we have 32-bit, 64-bit and x32).

**Comment by raphaelcohn** [comment]
Fix commit 8945848b7c5530921007ff2a5d792ad264b53c6e

**Comment by raphaelcohn** [comment]
Try this [Release](https://github.com/raphaelcohn/swaddle/releases/tag/release_2015.0429.1911-1)

**Comment by ringods** [comment]
@raphaelcohn My package is correctly created!  :tada: :+1: 

However, the script still fails with this as output:
```
/usr/bin/swaddle: 21686: cd: can't cd to /pipeline/source/target/download/apt/dists/rq-web-api-elx/multiverse/binary-i386
```
FYI, the folder isn't there. I don't have an i386 package and also don't need it.

**Comment by raphaelcohn** [comment]
* Could you send me a gist, please? It's a bug.
* The creation of `binary-i386` is quite deliberate when creating apt repositories. This is because an `all` package would belong in all supported Debian apt repos, and a valid repository structure would have all Debian architectures, even though they didn't necessarily contain packages.
* swaddle is designed to build multiple packages at once, and even include third party packages (as long as they're placed in the pool manually; this could change). This also supports this design.

**Comment by raphaelcohn** [comment]
Right, you can suppress i386 using `swaddle_apt architectures`; when this is unset, it defaults to `amd64` `i386`. I've fixed the bug I think that tries to pushd to this folder (we wrap `cd` to create `pushd` on shells that don't have it).

**Comment by ringods** [comment]
Filed as #28
