### ISSUE TITLE
ln: failed to create hard link / Invalid cross-device link

### ISSUE THREAD

**Issue by ringods** [raphaelcohn/swaddle#31]
While swaddling, I get this:

```
ln: failed to create hard link ‘/pipeline/source/target/download/apt/dists/rq-web-api-elx/multiverse/binary-amd64/rq-web-api-elx_1.0-1_amd64.deb.Packages’ => ‘/tmp/swaddle.SqALnLMzPP77/apt/package’: Invalid cross-device link
```

In one of my previous gists, I find these consecutive instructions:

```
+ ln -f /tmp/swaddle.29femJl46beA/apt/package /pipeline/source/target/download/apt/dists/rq-web-api-elx/multiverse/binary-amd64/rq-web-api-elx_2015.0506.0806-2_amd64.deb.Packages
+ rm /tmp/swaddle.29femJl46beA/apt/package
```

Can you change this to a `mv` command? Hard links don't work over different mount points / file systems.

**Comment by raphaelcohn** [comment]
I might be able to change it to a `ln || mv` or something . The reason for the hard link at this juncture was probably for performance. Let me take a look.

**Comment by raphaelcohn** [comment]
Right, I can change *some* of the hard links. Two I can't change are related to RPM macros - due to the horribly broken design of `rpmbuild`, these need to exist as the same file in two places. However, they're both files in the same directory, so shouldn't be affected by cross-device stuff.

There are two other locations that use them - I'll investigate further.

**Comment by raphaelcohn** [comment]
Right, of the two remaining, one definitely needs to stay (Yum repo GPG keys), because these files are served up usually via HTTP and some webservers don't work without a lot of configuration noise with symlinks. Again, though, these are for files in the same directory. One left to go...

**Comment by ringods** [comment]
@raphaelcohn currently, I'm not into RPM packaging so no need for changes there.

**Comment by raphaelcohn** [comment]
Fixed in commit 61c5d7ed899ee0e9314abf6f764d63a37639226b . I'll make a release.

**Comment by raphaelcohn** [comment]
Release is [here](https://github.com/raphaelcohn/swaddle/releases/tag/release_2015.0513.0920-1)

**Comment by ringods** [comment]
Tnx!!
