### ISSUE TITLE
bug: core_dependency_packageManager: parameter not set

### ISSUE THREAD

**Issue by layershifter** [raphaelcohn/swaddle#35]
Hello, @raphaelcohn 

I'm trying to run **swaddle**, but have startup error:

> /usr/bin/swaddle: 26466: /usr/bin/swaddle: core_dependency_packageManager: parameter not set

Error is there:

``` bash
swaddle_ensureGnupgCurlIsPresent ().
{
    if [ ${core_dependency_packageManager} = 'Debian' ]; then
        if ! core_path_isReadableNonEmptyFilePath /usr/share/doc/gnupg-curl/changelog.Debian.gz; then
            core_dependency_check_${core_dependency_packageManager}_packageManager gnupg-curl;
        fi;
    fi
}
```

Looks that bug is in `shellfire/core`. 

---

Swaddle was installed from github repo.
Distro: Ubuntu 14.04.5 LTS amd64

``` bash
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:    14.04
Codename:   trusty
```

Thanks.

**Comment by raphaelcohn** [comment]
Thanks for the report. I don't have time at the moment to investigate, but could you adjust swaddle to run as `set -x` and see the backtrace? `core_dependency_packageManager` is fairly fundamental - it's part of the shellfire framework and I'm surprised it's not set. Alternatively, you can run swaddle directly from the GitHub repo.

**Comment by layershifter** [comment]
I posted [trace](https://gist.github.com/layershifter/32fe44a146b76270b57884f4921c06b5) there.
